spring:
  kafka:
    consumer:
      snapshots-group-id: "snapshot.group.id"
      group-id: "hubEvent.group.id"
      enable-auto-commit: 'false'
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      snapshots-deserializer: "ru.yandex.practicum.deserializer.SensorSnapshotDeserializer"
      value-deserializer: "ru.yandex.practicum.deserializer.HubEventDeserializer"
      client-id: "HubEventConsumer"
      snapshots-client-id: "SnapshotsConsumer"
    bootstrap-servers: "localhost:9092"
  datasource:
    driverClassName: "org.postgresql.Driver"
    password: "password"
    username: "username"
    url: "jdbc:postgresql://localhost:5432/scenario-db"
  jpa:
    hibernate:
      ddl-auto: "none"
    show_sql: "true"
    properties:
      hibernate:
        format_sql: "true"
  sql:
    init:
      mode: "always"
grpc:
  client:
    hub-router:
      address: "static://localhost:59090"
      enableKeepAlive: "true"
      keepAliveWithoutCalls: "true"
      negotiationType: plaintext
topics:
  hub-event-topic: "telemetry.hubs.v1"
  snapshots-topic: "telemetry.snapshots.v1"
